services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge
